apiVersion: klot.io/v1
kind: KlotIOApp
metadata:
  name: mysql.klot.io
spec:
  namespace: mysql
  description: MySQL Server - Kloud of Things I/O
  manifests:
  - path: kubernetes/db.yaml
  settings:
  - name: storage
    description: Required to place MySQL
    node: enabled
