apiVersion: klot.io/v1
kind: App
metadata:
  name: mysql.klot.io
  description: MySQL Server - Kloud of Things I/O
spec:
  source:
    site: github.com
    repo: klot-io/mysql
  namespace: mysql-klot-io
  manifests:
  - path: kubernetes/namespace.yaml
  - path: kubernetes/db.yaml
  labels:
  - name: storage
    description: Required to place MySQL
    value: enabled
    master: true
