apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: mysql
spec:
  template:
    spec:
      containers:
      - name: mysql
        image: mysql-klot-io
        imagePullPolicy: Never
