apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: mysql-klot-io
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      nodeSelector:
        mysql.klot.io/storage: enabled
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
      - name: mysql
        hostPath:
          path: /home/pi/storage/mysql.klot.io
      containers:
      - name: mysql
        image: klotio/mysql:0.1
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: 'yes'
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: mysql-klot-io
spec:
  selector:
    app: db
  type: ClusterIP
  clusterIP: None
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
